version: "3.1"

services:
  albeniz-db:
    container_name: albeniz-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myDatabaseAdminUser
      POSTGRES_PASSWORD: aGivenAdminPassword
      POSTGRES_DB: albeniz_db
    ports:
      - 5432:5432
